[workspace]
resolver = "2"
members = [
    "crates/somite-ir",
    "crates/somite-ops",
    "crates/somite-nextflow",
    "crates/somite-cook",
    "crates/somite-paper",
    "crates/somite-cli",
    "crates/somite-server",
    "crates/somite-bundle",
]

[workspace.package]
edition = "2021"
license = "Apache-2.0"
version = "0.1.0"
