import { safeSourcePath } from "@somite/workflow/nextflowSource";
import type { NextflowConfigScalar } from "@somite/workflow/nextflowConfigExpression";

const encoder = new TextEncoder();
const MAX_BINDINGS = 10_000;
const MAX_WRAPPER_BYTES = 2 * 1024 * 1024;
const PARAMETER_NAME = /^[A-Za-z_][A-Za-z0-9_]*$/;

export const SOURCE_EFFECTIVE_CONFIG = ".somite/run/source-effective-nextflow.config";

function singleQuoted(value: string) {
  let rendered = "'";
  for (const character of value) {
    const point = character.codePointAt(0)!;
    rendered += character === "\\" ? "\\\\"
      : character === "'" ? "\\'"
        : character === "\n" ? "\\n"
          : character === "\r" ? "\\r"
            : character === "\t" ? "\\t"
              : character === "\b" ? "\\b"
                : character === "\f" ? "\\f"
                  : point < 32 || point === 127
                    ? `\\u${point.toString(16).padStart(4, "0")}`
                    : character;
  }
  return `${rendered}'`;
}

function scalar(value: NextflowConfigScalar) {
  if (typeof value === "string") return singleQuoted(value);
  if (typeof value === "number") {
    if (!Number.isFinite(value)) throw new Error("source config binding numbers must be finite");
    return JSON.stringify(value);
  }
  if (value === null) return "null";
  return value ? "true" : "false";
}

function relativeInclude(path: string) {
  if (!safeSourcePath(path) || path.startsWith(".somite/")) {
    throw new Error(`source config wrapper cannot include unsafe path ${path}`);
  }
  return `../../${path}`;
}

/**
 * Render the one effective `-C` input used by native inspection and execution.
 * Bindings appear on both sides of the source configs: the first copy closes
 * parameter-dependent includes, and the second preserves user overrides over
 * source defaults. The frozen Somite policy is always applied last.
 */
export function renderSourceConfigWrapper(
  rootConfigPaths: readonly string[],
  bindings: Readonly<Record<string, NextflowConfigScalar>>,
  executionConfigPath: string,
) {
  if (!safeSourcePath(executionConfigPath)
    || !executionConfigPath.startsWith(".somite/run/")
    || executionConfigPath === SOURCE_EFFECTIVE_CONFIG) {
    throw new Error(`source config wrapper has invalid execution policy path ${executionConfigPath}`);
  }
  const roots = [...new Set(rootConfigPaths)];
  if (roots.length !== rootConfigPaths.length) throw new Error("source config wrapper has duplicate root configs");
  const entries = Object.entries(bindings).sort(([left], [right]) => left.localeCompare(right));
  if (entries.length > MAX_BINDINGS) throw new Error(`source config wrapper exceeds ${MAX_BINDINGS} bindings`);
  const assignments = entries.map(([name, value]) => {
    if (!PARAMETER_NAME.test(name)) throw new Error(`source config wrapper has invalid parameter name ${name}`);
    return `params.${name} = ${scalar(value)}`;
  });
  const policyName = executionConfigPath.slice(".somite/run/".length);
  if (!policyName || policyName.includes("/")) throw new Error("source execution policy must be beside its wrapper");
  const lines = [
    "// Generated by Somite. This file is part of the frozen execution closure.",
    ...assignments,
    ...roots.map((path) => `includeConfig ${singleQuoted(relativeInclude(path))}`),
    ...assignments,
    `includeConfig ${singleQuoted(policyName)}`,
    "",
  ];
  const bytes = encoder.encode(lines.join("\n"));
  if (bytes.byteLength > MAX_WRAPPER_BYTES) throw new Error(`source config wrapper exceeds ${MAX_WRAPPER_BYTES} bytes`);
  return bytes;
}
